name: scp files
on:
  push:
    branches:
      - master
env:
  AZURE_WEBAPP_NAME: sispar    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './dist/sispar-app'      # set this to the path to your web app project
  NODE_VERSION: '12.x'                # set this to the node version to use
  
jobs:
  build:
 
    # using Ubuntu
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install and build
 
    - run: npm install
    - run: npm install -g @angular/cli > /dev/null
    - run: ng build --prod
 
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      env:
        HOST: ftps://waws-prod-dm1-083.ftp.azurewebsites.windows.net/site/wwwroot
        USERNAME: sispar\$sispar
        PORT: 21
        PASSWORD: 5wjXxDivFlJf5JFkRzL3JnC0hx7ZTebgJuqMkP7GTEsZetQiAvvlg3XcJjZ0
      with:
        source: "./dist/sispar-app/"
        target: "./"
        strip_components: 3 # this is important
 
